%PS3CONTROLLER PS3 controller interface.
%
% Copyright 2015 Mikhail S. Jones

classdef PS3Controller < handle

  % PROTECTED PROPERTIES ==================================================
  properties (Access = protected)
    axes@double vector = zeros(1,4)
    buttons@double vector = zeros(1,17)
    dt@double scalar = 0.001
  end % properties

  % PUBLIC METHODS ========================================================
  methods
    function update(obj, axes, buttons)
    %UPDATE Update PS3 controller object with controller data.

      % Update joysticks
      obj.axes = reshape(axes(1:4), 1, []);

      % Update buttons
      obj.buttons = reshape(buttons(1:17), 1, []).*(obj.buttons + obj.dt);
    end % update

    function ps3 = struct(obj)
    %STRUCT Convert object to a strucutre.

      ps3 = struct(...
        'leftStickX', obj.axes(1), ...
        'leftStickY', -obj.axes(2), ...
        'rightStickX', obj.axes(3), ...
        'rightStickY', -obj.axes(4), ...
        'select', obj.buttons(1), ...
        'l3', obj.buttons(2), ...
        'r3', obj.buttons(3), ...
        'start', obj.buttons(4), ...
        'up', obj.buttons(5), ...
        'right', obj.buttons(6), ...
        'down', obj.buttons(7), ...
        'left', obj.buttons(8), ...
        'l2', obj.buttons(9), ...
        'r2', obj.buttons(10), ...
        'l1', obj.buttons(11), ...
        'r1', obj.buttons(12), ...
        'triangle', obj.buttons(13), ...
        'circle', obj.buttons(14), ...
        'cross', obj.buttons(15), ...
        'square', obj.buttons(16), ...
        'ps', obj.buttons(17));
    end % struct
  end % methods
end % classdef
